name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run tests
        run: python3 -m pytest

      - name: Send email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: yonatan.voi
          password: {{secrets.GMAIL_PASSWORD}}
          subject: Build is over
          body: Some code was pushed into the repo
          to: yonatan.voi@gmail.com
          from: yonatan.voi@gmail.com
