name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip3 install -r requirements.txt

      - name: Run tests & coverage
        run: pytest --cov=main tests/

      - name: Login to Docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: build & push
        run: ./build_my_image.sh

      - name: Send email
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: yonatan.voi
          password: ${{secrets.GMAIL_PASSWORD}}
          subject: Build is over
          body: |
            The build process in ${{ github.repository }} has completed.
            Status: ${{ job.status }}
          to: yonatan.voi@gmail.com
          from: yonatan.voi@gmail.com
